### ISSUE TITLE
addition of first questline

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#1]
### Describe the feature

with tinkers construct being the first questline is alright, but brand new playyers who open up the quest book and see the tinkers construct questline wont know what any of it means, just some pictures of gravel/sand/clay and a square thing

sure you do have an arrow showing hovering over the left eveals all the questlines but they will get more confused as they dont know where to start. Maybe have one "big" quest that they click on that explains where they can go from there

i dont think they will know how to interact, bearing in mind the closest thing they know is a vanilla book
some information may be useful such as

- left click dragging the screen to "move"

- scrolling to zoom in and out

- you can click the "blinking" circle things

- with a quest open, you can "pin it"

- even if its dark and not blinking, you can still se what the quest is for

- right clicking a quest shows what its pre-requsites are and what it unlocks

### Reasons why this should be added

when the player first opens up the questbook they wont know what to do

because, assuming they have NEVER touched, or even seen, anything modded before, the most advanced thing they would know is how to use a book, crafter or maybe a command block

### Additional context

![image](https://github.com/user-attachments/assets/1f6414b1-88ac-412d-b242-fac22e194809)

**Comment by Atricos** [comment]
I think some of these should be obvious, like dragging the screen, or left clicking on quests. But yeah, I could add some of them.

**Comment by Atricos** [comment]
I added a Welcome quest that explains some of these.
