### ISSUE TITLE
an introductory quest for each page

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#2]
### Describe the feature

i see going through the questlines, none of them have a quest saying what the mod is about, what it is for nor what the player should expect going through it. For example

astral sorcery being a lot of multiblocks aswell as personal new "potion-like" buffs that are infinite (might need to explain, maybe in a sepperate quest covering all of the mods, such as https://github.com/Atricos/MyFirstAdventurePack/issues/1)

apotheosis changes how cactus, bamboo and sugarcane grow to be infinitely tall, it adds "affixed items" that are special tools with additional effects

colossal chests are bbeegg chests but also allow for more storage with tiers

atum/twilight forests are mods that can be played without ever taking foot in the overworld, as a "standalone dimension" if you like. Offering boss fights that require "thinking out of the box"

### Reasons why this should be added

to help tell players what they should expect playing with the mods. Yes jumping in feet first is always fun, but its not fun having no idea what the mod "is about" and therefore not really knowing why the mod exists or why people use it other than "more stuff"

**Comment by Atricos** [comment]
Alright, good idea

**Comment by Atricos** [comment]
I added this for Tinkers' Construct and Astral Sorcery in 1.1, and I didn't see the need for the other questlines. Apotheosis is explained in the Enchanting Table quest, and the exploration questlines are explained step by step as the player delves deeper into each mod.
