### ISSUE TITLE
tinkers tool upgrades

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#3]
### Describe the feature

after reading all of the tinkers books and quests, i dont see anywhere that mentions that the player can freely swap parts whenever they like, maygbe part of the tool station quest as that already mentions making a tool

Furthermore, you may want to explain that different parts have different qualities, so players who want a fast too may want to go for cobalt, or for durability to go for tinkers bronze or to go for manyullyn for more damage

### Reasons why this should be added

a player might assume once a tool is made, they cannot change it, since in vanilla there is no mechanic to swap parts of any tools to change their statistics

**Comment by Atricos** [comment]
Mentioned in 2 quests that it is possible to replace parts. I don't see the reason for explaining that the parts have different qualities, as this is stated on every part as well as the interface when creating the tool.
