### ISSUE TITLE
astral sorcery questline needs a slight tweak

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#4]
### Describe the feature

the resonating wand should ideally be before the rock crystal quest, because when you hold the wand, it makes the ore "glow", provided it is night time or you are in pitch black at bedrock level

this is why default the wand can be made in either the crafting table or an altar, as it aids searching

![image](https://github.com/user-attachments/assets/755b8c4b-f8f8-4f6d-b020-aa439f094661)

### Reasons why this should be added

new players wont know that holding the wand makes locating the ore far easier, otherwise its far far FAR harder than ancient debris blindly searching for it

**Comment by Atricos** [comment]
I tested this, and the wand doesn't seem to glow even if I'm in pitch black and at bedrock level. But I did remove the dependency from the Table to the Wand.

**Comment by Atricos** [comment]
In 1.1, I removed the dependency, and changed back the Astral Table recipe to the default one.
