### ISSUE TITLE
astral sorcery cannot be progressed by crafting alone

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#5]
### Modpack version

1.0

### Description

by having the astral sorcery luminous crafting table as a "hand crafted" recipe that is without astral sorcery collector crystal, the astral tome will not progress or unlock further

In the astral tome it tells the player how they should get the table
"By placing a crafting table near an academy shrine's collector crystal"

![image](https://github.com/user-attachments/assets/b02f3f91-ce9f-4694-8480-c496209a8518)
![image](https://github.com/user-attachments/assets/f8e7d047-96d0-428a-86bd-e2071bd4c4fe)
![image](https://github.com/user-attachments/assets/2702acc9-0659-46aa-aa3f-a685cab73eab)

### Steps to reproduce

crafting a table by hand will not unlock astral tome pages (which the quests tell you to do), but placing a crafting table next to a collector will

### Expected behavior

N/A

**Comment by redgoblin88** [comment]
update: the table will not "transform" if the collector crystal has an obstructed direct view of the sky

**Comment by Atricos** [comment]
Fixed in 1.1. Noted the method of transformation in the quest book, as well as having to give the Collector Crystal a direct view to the sky.
