### ISSUE TITLE
[1.1] Various Typos and Grammar Problems in Quests

### ISSUE THREAD

**Issue by KingOfThings56** [Atricos/MyFirstAdventurePack#6]
### Modpack version

1.0

### Where is the typo located?

Across various chapters and quests in the quest book. Exact quests and typos are listed in the Exact Fix section.

### Exact fix

Tinkers Chapter:
- Seared Fuel Tank quest (left side): "Metler" should be "Melter"
- Crafting Station quest: Unnecessary semicolon, should be a comma
- Tool Parts quest: "Veiin" has an extra i, should be Vein

Apotheosis:
- Melonshelf quest: "internal" should be "interval" at the end
- All three Charms quests: "its" at the end should be "it's"
- Anvil quest: The last sentence should be reworded from "...splitting the enchantments too of course." I suggest "...splitting the enchantments as well.", but other wordings would work too, of course.

Astral Sorcery:
- Impulsion Wand quest: "act" in the first sentence should be "acts"
- Traversal Wand: "Dash and Blink modes" should be changed to either "Dash mode and Blink mode", or "Dash and Blink". Additionally, "the user will be dashes forward" should be either "the user will dash forward" or some variant of "the user will be launched forward"
- Starlight Infuser quest: "The holes is where..." should be "The holes are where..." in the fifth paragraph
- Stellar Refraction Table quest: "SHift Right Click" should be "Shift Right Click", and "more powerful than vanilla Enchanted Books" could be reworded as "more powerful Enchanted Books than vanilla"
- Advancement: Iridescent Altar quest: "blcks" should be "blocks"

Utilities:
- Colossal Chest Core quest: "build" should be "built"
- Guide to Animal Companionship quest: "However in return" should be "However, in return"
- Bound Scroll quest: "Return Scroll" should be "Bound Scroll", and "helf" should be "held"

Twilight Forest:
- Minoshroom Trophy quest: "one may find the Minoshroom boss room...:" doesn't need the colon at the end
- Hydra Trophy quest: "When one consumes the Meef Stroganoff, dropped by the Minoshroom;" should end with a comma instead of a semicolon

Atum:
- Any #atum:artifact quest: "meelee" should be "melee"
- 2x Godforged Block quest: Same issue as above, "meelee" should be "melee"

The Abyss:
- Advancement: Loran quest: "Loran Flower" should be "Loran Flowers"
- Visit Dimension: theabyss:the_abyss quest: "Spening" should be "Spending"
- Somnium Extractor quest: "This machine allows for the creation of Somnium a material for spellcasting." needs a comma between "Somnium" and "a"
- Phantom Essence quest: "withsome" should be "with some", and "a a" should just be "a"

Draconic Evolution:
- Dragon Drops quest: "haelth" should be "health", and "There are some unique loot" should be "There is some unique loot"
- 8x Draconic Core quest: "mod" should be "mods"
- Draconic Staff of Power quest: "ridicolously" should be "ridiculously"
- The Chaos Guardian quest: "The quickly bail" should be "Then quickly bail"

**Comment by Atricos** [comment]
Thank you King, I really appreciate this!

**Comment by Atricos** [comment]
I fixed everything, except for the Minoshroom Trophy one. The colon would indicate that the following picture shows what the Minoshroom boos room looks like.

**Comment by KingOfThings56** [comment]
That one is fine to stay, I just thought that it wasn't necessary. I was also comparing it to the Hydra quest, which doesn't have a semicolon in the same scenario.

**Comment by KingOfThings56** [comment]
New typos in version 1.1:

Tinker's Construct:
- Just Enough Items quest: the last paragraph explains how to use $, but uses # in the example
- Inventory Sorter quest: "Scrool Wheel Up" misspells scroll

Astral Sorcery:
- About Astral Sorcery quest: "a taste at magic mods" should be "a taste of magic mods", and "point" in the fourth paragraph should be "points"

Utilities:
- Gun Workbench quest: "uload" should be "unload"

I didn't want to open a new issue for this since there were so few, so I just added them here.

**Comment by Atricos** [comment]
I'm starting to think I'm dyslexic. Anyways, thank you for finding these.

**Comment by Atricos** [comment]
Fixed them in 1.2.

**Comment by Atricos** [comment]
All typos _seem_ to be fixed for now, so I'll close this. Feel free to open another bug report if more are found.
