### ISSUE TITLE
Questbook Inaccuracies

### ISSUE THREAD

**Issue by BenRodkin** [Atricos/MyFirstAdventurePack#7]
### Modpack version

1.1

### Description

Collection of issues in the questbook.

More will be added if I find them.

### Steps to reproduce

1) TiC Casting Basin
![image](https://github.com/user-attachments/assets/65540354-e974-4efc-96a0-5431bd14e86f)
There are 2 quests that ask for a casting basin and give the same rewards, but have different descriptions.

~~2) TiC Seared Bricks
![image](https://github.com/user-attachments/assets/4323157e-b8db-477e-aad2-46a293483bd5)
16 seared bricks has prereq of smeltery controller when you need a smeltery to craft the smeltery controller.~~
I was unfamiliar with modern TiC.

3) TiC Seared Fuel Tank
![image](https://github.com/user-attachments/assets/81191f94-5d11-402b-b87a-4545c085ca50)
Same as Casting Basin; 2 different quests that ask for a seared fuel tank and give same rewards, but have different descriptions.

### Expected behavior

1) TiC Casting Basin
Combine both descriptions into one quest

~~2) TiC Sear Bricks
Change smelter controller dependency to a dependent~~

3) ToC Sear Fuel Tank
Combine both descriptions into one quest

**Comment by Atricos** [comment]
This is intended. Both multiblocks require a Casting Basin and a Fuel Tank.

**Comment by BenRodkin** [comment]
Agreed, at the moment it seems like you can make the full smeltery without a Seared Melter (as in older TiC versions) which leads to confusion for those only familiar with said older TiC versions. 

It may also be worth moving the location of the quests so the full smeltery specific blocks are all in one spot instead of scattered about and intermixed with the Seared Melter blocks.
![image](https://github.com/user-attachments/assets/c9eec6e6-a4d5-41f4-b605-587601935655)

**Comment by Atricos** [comment]
They aren't scattered. They are right where the picture below shows them. This helps build the structure for the first time imo.

**Comment by Atricos** [comment]
In 1.2, I've added these arrows to indicate which quest refers to which blocks of the structure. Hopefully it's less confusing this way.
![image](https://github.com/user-attachments/assets/7b0cd1a9-3657-4e6b-a51f-e29b038b9cf3)
Additionally, I made it so the Smeltery unlocks after all parts of the Melter have been crafted.
