### ISSUE TITLE
apotheosis book has no recipe

### ISSUE THREAD

**Issue by redgoblin88** [Atricos/MyFirstAdventurePack#8]
### Modpack version

1.1

### Description

the apotheosis manual, "Chromicle of shadows" has no crafting recipe.

Yes you are given one, but the player might acidently loose it and need to get it back

### Steps to reproduce

N/A

### Expected behavior

uuh a recipe?

**Comment by Atricos** [comment]
Added a recipe in 1.2 with a Book and a piece of purple dye.
